/* eslint-disable react-native/no-unused-styles */
import { StyleSheet, Platform, StatusBar } from 'react-native';

export const getStyles = (t) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: t.bg,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    header: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      backgroundColor: t.headerBg,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    headerSideArea: { width: 80, justifyContent: 'center' },
    headerTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700', color: t.textMain },
    headerLogo: { width: 140, height: 44, alignSelf: 'center' },
    headerButton: { fontSize: 15, color: t.primary },
    headerCancelButton: { fontSize: 15, color: t.textSub },
    headerSaveButton: { fontSize: 16, fontWeight: 'bold', color: t.primary },
    editButtonText: { fontSize: 15, color: t.primary, fontWeight: '600' },
    clearBoughtText: { fontSize: 12, color: t.primary, fontWeight: '600' },
    clearAllText: { fontSize: 12, color: '#DC3545', fontWeight: '600' },

    bottomNavBar: {
      flexDirection: 'row',
      height: Platform.OS === 'ios' ? 84 : 88,
      paddingBottom: Platform.OS === 'ios' ? 24 : 32,
      backgroundColor: t.navBg,
      borderTopWidth: 1,
      borderTopColor: t.border,
      alignItems: 'center',
      justifyContent: 'space-around',
    },
    navTabItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
      borderRadius: 14,
    },
    navTabLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: t.textMuted,
      marginTop: 2,
    },
    navTabLabelActive: {
      color: t.primary,
      fontWeight: 'bold',
    },
    navBadge: {
      position: 'absolute',
      right: -8,
      top: -3,
      backgroundColor: '#E67E22',
      borderRadius: 10,
      paddingHorizontal: 4,
      paddingVertical: 1,
      minWidth: 16,
      alignItems: 'center',
    },
    navBadgeText: { color: '#FFF', fontSize: 9, fontWeight: 'bold' },

    homeScrollView: { padding: 14, paddingBottom: 100 },
    headlineBarHome: {
      backgroundColor: t.isDark ? '#2E2210' : '#FEF9E7',
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 10,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: '#FAD7A0',
    },
    headlineTextHome: { fontSize: 12, fontWeight: 'bold', color: '#D35400', lineHeight: 18 },

    homeSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 8,
    },
    homeSectionTitle: { fontSize: 15, fontWeight: 'bold', color: t.textMain },

    homeEmptyCard: {
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
      borderStyle: 'dashed',
    },
    homeEmptyCardTitle: { fontSize: 13, fontWeight: 'bold', color: t.textSub, marginBottom: 4 },
    homeEmptyCardSub: { fontSize: 11.5, color: t.textMuted, lineHeight: 17 },

    homeRecommendCard: {
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1.5,
      borderColor: '#F5D2B3',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    homeRecommendLeft: { flex: 1, marginRight: 10 },
    homeRecommendTag: { fontSize: 11, fontWeight: 'bold', color: t.primary, marginBottom: 4 },
    homeRecommendTitle: { fontSize: 16, fontWeight: 'bold', color: t.textMain, marginBottom: 4 },
    homeRecommendSub: { fontSize: 11.5, color: t.textMuted },
    homeRecommendBtn: {
      backgroundColor: t.primary,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
    },
    homeRecommendBtnText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },

    recentMealCard: {
      backgroundColor: t.cardBg,
      borderRadius: 10,
      padding: 10,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
    },
    recentMealRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    recentMealDate: { fontSize: 12, fontWeight: 'bold', color: t.primary, width: 55 },
    recentMealTitle: { flex: 1, fontSize: 13.5, color: t.textMain, fontWeight: '600' },

    horizontalCard: {
      width: 160,
      backgroundColor: t.cardBg,
      borderRadius: 12,
      marginRight: 10,
      borderWidth: 1,
      borderColor: t.border,
      overflow: 'hidden',
    },
    horizontalThumb: { width: '100%', height: 95, backgroundColor: t.chipBg },
    horizontalThumbPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    horizontalCardBody: { padding: 8 },
    horizontalCardTitle: { fontSize: 13, fontWeight: 'bold', color: t.textMain, marginBottom: 4 },
    horizontalCardMeta: { flexDirection: 'row', alignItems: 'center', gap: 4 },

    searchBarContainer: {
      backgroundColor: t.headerBg,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    searchInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
    },
    filterTabsScroll: { flexDirection: 'row', marginTop: 8 },
    filterTab: {
      paddingVertical: 5,
      paddingHorizontal: 11,
      borderRadius: 16,
      backgroundColor: t.chipBg,
      marginRight: 6,
      borderWidth: 1.5,
      borderColor: '#D4C2A8',
    },
    filterTabActive: { backgroundColor: t.primary, borderColor: t.primary },
    filterTabActiveUserOnly: { backgroundColor: '#D35400', borderColor: '#D35400' },
    filterTabActiveRequested: { backgroundColor: '#E67E22', borderColor: '#E67E22' },
    filterTabActiveWant: { backgroundColor: '#27AE60', borderColor: '#27AE60' },
    filterTabActiveBento: { backgroundColor: '#E67E22', borderColor: '#E67E22' },
    filterTabActiveMealPrep: { backgroundColor: '#2980B9', borderColor: '#2980B9' },
    filterTabActivePreset: { backgroundColor: '#8E44AD', borderColor: '#8E44AD' },
    filterTabText: { fontSize: 12, fontWeight: '600', color: t.textSub },
    filterTabTextActive: { color: '#FFF' },

    listContent: { padding: 14, paddingBottom: 110 },
    card: {
      flexDirection: 'row',
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: t.border,
    },
    cardRequestedHighlight: {
      borderColor: '#F39C12',
      backgroundColor: t.isDark ? '#2E2210' : '#FEF9E7',
    },
    thumbnail: { width: 80, height: 80, borderRadius: 8, backgroundColor: t.chipBg },
    thumbnailPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    cardBody: { flex: 1, marginLeft: 12, justifyContent: 'space-between' },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { flex: 1, fontSize: 15, fontWeight: '700', color: t.textMain, marginRight: 6 },
    cardBadgesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginVertical: 3 },
    cardBadgeItem: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      backgroundColor: t.bg,
      borderWidth: 1,
      borderColor: t.border,
    },
    cardBadgeItemText: { fontSize: 10, fontWeight: '600', color: t.textSub },
    cardNotes: { fontSize: 12, color: t.primary, lineHeight: 16 },
    cardNotesEmpty: { fontSize: 11, color: t.textMuted },
    cardMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
    cardDate: { fontSize: 10, color: t.textMuted },

    fab: {
      position: 'absolute',
      right: 18,
      bottom: 30,
      backgroundColor: t.primary,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      elevation: 6,
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 5,
      zIndex: 10,
    },
    fabText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },

    detailImage: { width: '100%', height: 200, borderRadius: 12, marginBottom: 10 },
    detailTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
    detailTitle: { flex: 1, fontSize: 20, fontWeight: 'bold', color: t.textMain, marginRight: 8 },
    detailTagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
    detailTag: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: t.primaryLight,
      borderWidth: 1,
      borderColor: t.primaryBorder,
    },
    detailTagText: { fontSize: 11.5, fontWeight: '700', color: t.primary },

    bigCookStartBtn: {
      backgroundColor: t.primary,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    bigCookStartBtnText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },
    bigCookStartBtnActive: { backgroundColor: '#DC3545' },

    smartActionBar: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    smartActionBtn: {
      flex: 1,
      backgroundColor: t.cardBg,
      paddingVertical: 9,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    smartActionBtnActiveRequest: { backgroundColor: '#E67E22', borderColor: '#E67E22' },
    smartActionBtnText: { fontSize: 12, fontWeight: '700', color: t.textMain },
    smartActionBtnTextActive: { color: '#FFF' },

    noteSection: {
      backgroundColor: '#FFF8F0',
      padding: 12,
      borderRadius: 10,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
      borderWidth: 1,
      borderColor: '#F5E7D3',
    },
    noteSectionHeader: { fontSize: 13, fontWeight: 'bold', color: t.primary, marginBottom: 4 },
    noteText: { fontSize: 13, color: t.textMain, lineHeight: 18 },
    noteSectionEmpty: {
      backgroundColor: t.chipBg,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
      borderStyle: 'dashed',
    },
    noteTextEmpty: { fontSize: 12, color: t.textMuted, fontWeight: '500' },

    servingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: t.bg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      marginBottom: 10,
    },
    servingLabel: { fontSize: 12, fontWeight: 'bold', color: t.textSub },
    servingChips: { flexDirection: 'row', gap: 6 },
    servingChip: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: t.cardBg,
      borderWidth: 1,
      borderColor: t.border,
    },
    servingChipActive: { backgroundColor: t.primary, borderColor: t.primary },
    servingChipText: { fontSize: 11, fontWeight: '600', color: t.textSub },
    servingChipTextActive: { color: '#FFF', fontWeight: 'bold' },

    detailSection: {
      backgroundColor: t.cardBg,
      padding: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      marginBottom: 30,
    },
    sectionHeader: { fontSize: 15, fontWeight: 'bold', color: t.primary, marginBottom: 8 },
    recipeLineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 7,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    recipeLineRowChecked: { backgroundColor: t.bg, borderRadius: 6 },
    checkIcon: { fontSize: 15, marginRight: 6, marginTop: 2 },
    detailText: { fontSize: 14, color: t.textMain, lineHeight: 22 },
    cookingLineText: { flex: 1, fontSize: 17, color: t.textMain, lineHeight: 26, fontWeight: '500' },
    checkedLineText: { textDecorationLine: 'line-through', color: t.textMuted },

    addShoppingBar: {
      flexDirection: 'row',
      backgroundColor: t.headerBg,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
      gap: 8,
    },
    addShoppingInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
    },
    addShoppingBtn: { backgroundColor: t.primary, paddingHorizontal: 14, justifyContent: 'center', borderRadius: 8 },
    addShoppingBtnText: { color: '#FFF', fontSize: 13, fontWeight: 'bold' },
    shoppingItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    shoppingItemRowChecked: { opacity: 0.5 },
    shoppingItemCheckArea: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    shoppingCheckIcon: { fontSize: 18, marginRight: 10 },
    shoppingItemText: { fontSize: 15, color: t.textMain, fontWeight: '500' },
    shoppingItemTextChecked: { textDecorationLine: 'line-through', color: t.textMuted },
    shoppingItemDeleteBtn: { padding: 6 },
    shoppingItemDeleteText: { fontSize: 14, color: '#DC3545', fontWeight: 'bold' },

    content: { padding: 14 },
    editScrollContent: { paddingBottom: 100 },
    formCard: {
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
    },
    formCardHighlight: {
      backgroundColor: t.isDark ? '#162222' : '#F8FCFC',
      borderColor: t.primaryBorder,
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
    },
    formCardHeader: {
      fontSize: 15,
      fontWeight: 'bold',
      color: t.textMain,
      marginBottom: 12,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    formCardHeaderNoBorder: { fontSize: 15, fontWeight: 'bold', color: t.textMain },
    fieldLabel: { fontSize: 13, fontWeight: '700', color: t.textSub, marginBottom: 6 },
    requiredMark: { color: '#DC3545' },
    subLabelHelp: { fontSize: 11, color: t.textMuted, marginBottom: 8, lineHeight: 16 },

    inputTitle: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      fontWeight: '600',
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 12,
    },
    inputRegular: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 6,
    },
    categorySelectorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    categoryChip: {
      backgroundColor: t.chipBg,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
    },
    categoryChipSelected: { backgroundColor: t.primary, borderColor: t.primary },
    categoryChipText: { fontSize: 12, fontWeight: '600', color: t.textSub },
    categoryChipTextSelected: { color: '#FFF' },

    tagToggleRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
    tagToggleBtn: {
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
    },
    tagToggleBtnActive: { backgroundColor: t.primaryLight, borderColor: t.primary },
    tagToggleBtnText: { fontSize: 12, color: t.textSub, fontWeight: '600' },
    tagToggleBtnTextActive: { color: t.primary, fontWeight: 'bold' },

    familyRatingContainer: {
      backgroundColor: t.cardBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: t.border,
    },
    familyRatingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    familyMemberName: { flex: 1, fontSize: 13, fontWeight: '600', color: t.textMain, marginRight: 8 },
    starButtonGroup: { flexDirection: 'row', gap: 4 },
    starButton: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 6, backgroundColor: t.chipBg },
    starButtonActive: {
      backgroundColor: t.isDark ? '#332712' : '#FEF9E7',
      borderWidth: 1,
      borderColor: '#E67E22',
    },
    starButtonText: { fontSize: 11, color: t.textMuted, fontWeight: '500' },
    starButtonTextActive: { color: '#E67E22', fontWeight: 'bold' },

    noteInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: t.primaryBorder,
      minHeight: 60,
      fontSize: 14,
      color: t.textMain,
      textAlignVertical: 'top',
    },
    recipeTextInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: t.borderInput,
      minHeight: 110,
      fontSize: 14,
      color: t.textMain,
      lineHeight: 20,
      textAlignVertical: 'top',
    },

    deleteFormBtn: { marginTop: 10, marginBottom: 20, paddingVertical: 12, borderRadius: 10, backgroundColor: t.isDark ? '#3A1E1E' : '#FDE8E8', borderWidth: 1, borderColor: '#F8B4B4', alignItems: 'center' },
    deleteFormBtnText: { color: '#DC3545', fontSize: 14, fontWeight: 'bold' },
    resetDefaultBtn: { marginTop: 10, marginBottom: 20, paddingVertical: 12, borderRadius: 10, backgroundColor: t.isDark ? '#2A2035' : '#F4ECF7', borderWidth: 1, borderColor: '#D2B4DE', alignItems: 'center' },
    resetDefaultBtnText: { color: '#8E44AD', fontSize: 14, fontWeight: 'bold' },

    settingToggleRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
    settingOptionBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: 'center',
    },
    settingOptionBtnActive: { backgroundColor: t.primary, borderColor: t.primary },
    settingOptionText: { fontSize: 13, fontWeight: '600', color: t.textSub },
    settingOptionTextActive: { color: '#FFF' },

    familyIdDisplayBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 6,
    },
    familyIdText: { fontSize: 16, fontWeight: 'bold', color: t.primary, letterSpacing: 1.5 },
    familyIdInfoBtn: { backgroundColor: t.primaryLight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    familyIdInfoBtnText: { fontSize: 11, fontWeight: 'bold', color: t.primary },
    regenerateIdBtn: { paddingVertical: 6, alignItems: 'center', marginBottom: 10 },
    regenerateIdBtnText: { fontSize: 12, fontWeight: '600', color: t.primary },
    joinFamilyRow: { flexDirection: 'row', gap: 8 },
    joinFamilyInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
    },
    joinFamilyBtn: { backgroundColor: t.primary, paddingHorizontal: 16, justifyContent: 'center', borderRadius: 8 },
    joinFamilyBtnText: { color: '#FFF', fontSize: 13, fontWeight: 'bold' },

    memberHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
    memberCountBadge: { fontSize: 11, fontWeight: 'bold', color: t.primary, backgroundColor: t.primaryLight, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 10 },
    memberEditRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 8 },
    memberIndexLabel: { fontSize: 12, fontWeight: 'bold', color: t.textMuted, width: 22 },
    memberNameInput: { flex: 1, backgroundColor: t.inputBg, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, fontSize: 13, color: t.textMain, borderWidth: 1, borderColor: t.borderInput },
    memberDeleteBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#FDE8E8', justifyContent: 'center', alignItems: 'center' },
    memberDeleteBtnText: { color: '#DC3545', fontSize: 13, fontWeight: 'bold' },
    addMemberBtn: { marginTop: 10, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: t.primary, borderStyle: 'dashed', alignItems: 'center' },
    addMemberBtnText: { color: t.primary, fontSize: 12, fontWeight: 'bold' },
  });
