/* eslint-disable react-native/no-unused-styles */
import { StyleSheet, Platform, StatusBar } from 'react-native';

export const getStyles = (t) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: t.bg,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
// ★ ヘッダーの高さを広げる（52px ➔ 64px）
    header: {
      height: 64,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      backgroundColor: t.headerBg,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },

    // ★ ロゴサイズを大きく拡大（横140px / 縦46px）
    headerLogo: {
      width: 160,
      height: 76,
      alignSelf: 'center',
    },
    headerSideArea: { width: 70, justifyContent: 'center' },
    headerTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700', color: t.textMain },
    headerButton: { fontSize: 15, color: t.primary },
    headerCancelButton: { fontSize: 15, color: t.textSub },
    headerSaveButton: { fontSize: 16, fontWeight: 'bold', color: t.primary },
    editButtonText: { fontSize: 15, color: t.primary, fontWeight: '600' },
    clearBoughtText: { fontSize: 13, color: t.primary, fontWeight: '600' },
    // ★ 下部ボトムナビゲーションバー（5タブ固定）
    // ★ iOS / Android 両対応の下部ナビゲーションバー
    // ★ スマホ本体のナビゲーションバー（◀ ● ■）と重ならない設定
    bottomNavBar: {
      flexDirection: 'row',
      // Androidの「◀ ● ■」の高さを考慮して全体を90pxに確保
      height: Platform.OS === 'ios' ? 90 : 105,
      // 本体の「◀ ● ■」ボタンの高さ（約36〜40px）分、バーの中身を上に押し上げる
      paddingBottom: Platform.OS === 'ios' ? 30 : 50,
      backgroundColor: t.navBg,
      borderTopWidth: 1,
      borderTopColor: t.border,
      alignItems: 'center',
      justifyContent: 'space-around',
    },
// styles.js 内の navTabItem
    navTabItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
      // ★ 波紋がボタンの角丸の中で綺麗に広がる設定
      borderRadius: 12,
      overflow: 'hidden',
    },
    navTabIcon: {
      fontSize: 20,
      marginBottom: 2,
    },
    navTabLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: t.textMuted,
    },
    navTabLabelActive: {
      color: t.primary,
      fontWeight: 'bold',
    },
    navBadge: {
      position: 'absolute',
      right: 12,
      top: 2,
      backgroundColor: '#E67E22',
      borderRadius: 10,
      paddingHorizontal: 5,
      paddingVertical: 1,
      minWidth: 16,
      alignItems: 'center',
    },
    navBadgeText: { color: '#FFF', fontSize: 9, fontWeight: 'bold' },

    // ホーム画面スタイル
    homeScrollView: { padding: 14, paddingBottom: Platform.OS === 'ios' ? 110 : 90 },
    listContent: { padding: 14, paddingBottom: Platform.OS === 'ios' ? 110 : 90 },
    seasonalScroll: { padding: 14, paddingBottom: Platform.OS === 'ios' ? 110 : 90 },
    homeSearchRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    homeSearchInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
    },
    homeAddBtn: {
      backgroundColor: t.primary,
      paddingHorizontal: 14,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    homeAddBtnText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },

    headlineBarHome: {
      backgroundColor: t.isDark ? '#2E2210' : '#FEF9E7',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: '#FAD7A0',
    },
    headlineTextHome: { fontSize: 12, fontWeight: 'bold', color: '#D35400' },

    homeSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
      marginBottom: 10,
    },
    homeSectionTitle: { fontSize: 16, fontWeight: 'bold', color: t.textMain },
    homeSectionMore: { fontSize: 12, color: t.primary, fontWeight: '600' },

    // 直近の献立カード
    recentMealCard: {
      backgroundColor: t.cardBg,
      borderRadius: 10,
      padding: 12,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: t.border,
    },
    recentMealRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    recentMealDate: { fontSize: 12, fontWeight: 'bold', color: t.primary, width: 60 },
    recentMealTitle: { flex: 1, fontSize: 14, color: t.textMain, fontWeight: '600' },

// ★ ホームの横スクロールカード幅を広げて文字切れを防止
    horizontalCard: {
      width: 160, // 140から160に拡大
      backgroundColor: t.cardBg,
      borderRadius: 12,
      marginRight: 10,
      borderWidth: 1,
      borderColor: t.border,
      overflow: 'hidden',
    },
    horizontalThumb: { width: '100%', height: 95, backgroundColor: t.chipBg },
    horizontalThumbPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    horizontalCardBody: { padding: 8 },
    horizontalCardTitle: { fontSize: 13, fontWeight: 'bold', color: t.textMain, marginBottom: 4 },
    horizontalCardRating: { fontSize: 11, color: '#E67E22', fontWeight: 'bold' },

    // リスト画面スタイル
    searchBarContainer: {
      backgroundColor: t.headerBg,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    searchInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
    },
    filterTabsScroll: { flexDirection: 'row', marginTop: 8 },
// ★ くっきりと引き締まったフィルターボタン境界線
    filterTab: {
      paddingVertical: 5,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: t.chipBg,
      marginRight: 6,
      borderWidth: 1.5, // 1.5pxでくっきり
      borderColor: '#D4C2A8', // ぼやけない明確な境界線
    },
    filterTabActive: { backgroundColor: t.primary, borderColor: t.primary },
    filterTabActiveUserOnly: { backgroundColor: '#D35400', borderColor: '#D35400' }, // ★ わが家の登録タブ用
    filterTabActiveRequested: { backgroundColor: '#E67E22', borderColor: '#E67E22' },
    filterTabActiveWant: { backgroundColor: '#27AE60', borderColor: '#27AE60' },
    filterTabActivePreset: { backgroundColor: '#8E44AD', borderColor: '#8E44AD' },
    filterTabText: { fontSize: 12, fontWeight: '600', color: t.textSub },
    filterTabTextActive: { color: '#FFF' },
    filterTabTextActiveRequested: { color: '#FFF' },
    filterTabTextActiveWant: { color: '#FFF' },
    filterTabTextActivePreset: { color: '#FFF' },

    card: {
      flexDirection: 'row',
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: t.border,
    },
    cardRequestedHighlight: {
      borderColor: '#F39C12',
      backgroundColor: t.isDark ? '#2E2210' : '#FEF9E7',
    },
    thumbnail: { width: 80, height: 80, borderRadius: 8, backgroundColor: t.chipBg },
    thumbnailPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    cardBody: { flex: 1, marginLeft: 12, justifyContent: 'space-between' },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { flex: 1, fontSize: 15, fontWeight: '700', color: t.textMain, marginRight: 6 },
    categoryBadge: {
      backgroundColor: t.primaryLight,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: t.primaryBorder,
    },
    categoryBadgeText: { fontSize: 10, fontWeight: '700', color: t.primary },
    requestedBadge: { backgroundColor: '#E67E22', paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6 },
    requestedBadgeText: { fontSize: 10, fontWeight: 'bold', color: '#FFF' },
    wantToCookBadge: { backgroundColor: '#E8F8F5', borderWidth: 1, borderColor: '#A3E4D7', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
    wantToCookBadgeText: { fontSize: 10, fontWeight: 'bold', color: '#27AE60' },
    cardUncookedHint: { fontSize: 11, color: '#27AE60', fontWeight: '600', marginVertical: 3 },

    cardFamilyRatingRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginVertical: 3 },
    cardFamilyRatingItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.bg,
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: t.border,
    },
    cardFamilyMemberLabel: { fontSize: 10, color: t.textSub, marginRight: 4, fontWeight: '600' },
    cardFamilyMemberStars: { fontSize: 10, color: '#E67E22', fontWeight: 'bold' },
    cardNotes: { fontSize: 12, color: t.primary, lineHeight: 16 },
    cardNotesEmpty: { fontSize: 11, color: t.textMuted },
    cardMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
    cardDate: { fontSize: 10, color: t.textMuted },
    cardWebBadge: { fontSize: 10, color: '#2980B9', fontWeight: '500' },

    emptyContainer: { alignItems: 'center', marginTop: 60, paddingHorizontal: 32 },
    emptyIcon: { fontSize: 44, marginBottom: 10 },
    emptyText: { color: t.textSub, fontSize: 15, fontWeight: '600', textAlign: 'center' },
    emptySubText: { color: t.textMuted, fontSize: 12, marginTop: 6, textAlign: 'center', lineHeight: 18 },

// ★ iOS / Android 両対応のボタン位置
    fab: {
      position: 'absolute',
      right: 18,
      // レシピ一覧のすぐ上、ナビバーの上に綺麗に配置
      bottom: 20,
      backgroundColor: t.primary,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      elevation: 6,
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 5,
      zIndex: 10,
    },
    fabText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },

    // 旬の食材画面スタイル
    seasonalCard: {
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 16,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: t.border,
    },
    seasonalTitle: { fontSize: 18, fontWeight: 'bold', color: t.textMain, marginBottom: 6 },
    seasonalDesc: { fontSize: 13, color: t.textSub, lineHeight: 18, marginBottom: 12 },
    seasonalTagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    seasonalTagBtn: {
      backgroundColor: t.primaryLight,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: t.primaryBorder,
    },
    seasonalTagText: { fontSize: 13, color: t.primary, fontWeight: 'bold' },

    // 買い物リストスタイル
    addShoppingBar: {
      flexDirection: 'row',
      backgroundColor: t.headerBg,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
      gap: 8,
    },
    addShoppingInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
    },
    addShoppingBtn: { backgroundColor: t.primary, paddingHorizontal: 14, justifyContent: 'center', borderRadius: 8 },
    addShoppingBtnText: { color: '#FFF', fontSize: 13, fontWeight: 'bold' },
    shoppingItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    shoppingItemRowChecked: { opacity: 0.5 },
    shoppingItemCheckArea: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    shoppingCheckIcon: { fontSize: 18, marginRight: 10 },
    shoppingItemText: { fontSize: 15, color: t.textMain, fontWeight: '500' },
    shoppingItemTextChecked: { textDecorationLine: 'line-through', color: t.textMuted },
    shoppingItemDeleteBtn: { padding: 6 },
    shoppingItemDeleteText: { fontSize: 14, color: '#DC3545', fontWeight: 'bold' },

    // 共通カード ＆ フォーム
    content: { padding: 14 },
    editScrollContent: { paddingBottom: 100 },
    formCard: {
      backgroundColor: t.cardBg,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
    },
    formCardHighlight: {
      backgroundColor: t.isDark ? '#162222' : '#F8FCFC',
      borderColor: t.primaryBorder,
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
    },
    formCardHeader: {
      fontSize: 15,
      fontWeight: 'bold',
      color: t.textMain,
      marginBottom: 12,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    formCardHeaderNoBorder: { fontSize: 15, fontWeight: 'bold', color: t.textMain },
    fieldLabel: { fontSize: 13, fontWeight: '700', color: t.textSub, marginBottom: 6 },
    requiredMark: { color: '#DC3545' },
    subLabelHelp: { fontSize: 11, color: t.textMuted, marginBottom: 8, lineHeight: 16 },

    familyIdDisplayBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 6,
    },
    familyIdText: { fontSize: 16, fontWeight: 'bold', color: t.primary, letterSpacing: 1.5 },
    familyIdInfoBtn: { backgroundColor: t.primaryLight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    familyIdInfoBtnText: { fontSize: 11, fontWeight: 'bold', color: t.primary },
    regenerateIdBtn: { paddingVertical: 6, alignItems: 'center', marginBottom: 10 },
    regenerateIdBtnText: { fontSize: 12, fontWeight: '600', color: t.primary },
    joinFamilyRow: { flexDirection: 'row', gap: 8 },
    joinFamilyInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
    },
    joinFamilyBtn: { backgroundColor: t.primary, paddingHorizontal: 16, justifyContent: 'center', borderRadius: 8 },
    joinFamilyBtnText: { color: '#FFF', fontSize: 13, fontWeight: 'bold' },

    inputTitle: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      fontWeight: '600',
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 12,
    },
    inputRegular: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 6,
    },
    photoSelectBox: {
      height: 64,
      borderRadius: 8,
      backgroundColor: t.inputBg,
      borderWidth: 1,
      borderColor: t.borderInput,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 8,
    },
    photoSelectIcon: { fontSize: 18 },
    photoSelectText: { color: t.primary, fontSize: 13, fontWeight: '600' },
    photoPreviewWrapper: { position: 'relative' },
    foodPhotoPreview: { width: '100%', height: 160, borderRadius: 8 },
    changePhotoBtn: {
      position: 'absolute',
      right: 8,
      bottom: 8,
      backgroundColor: 'rgba(0,0,0,0.7)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    changePhotoBtnText: { color: '#FFF', fontSize: 11, fontWeight: '600' },

    categorySelectorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    categoryChip: {
      backgroundColor: t.chipBg,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
    },
    categoryChipSelected: { backgroundColor: t.primary, borderColor: t.primary },
    categoryChipText: { fontSize: 12, fontWeight: '600', color: t.textSub },
    categoryChipTextSelected: { color: '#FFF' },

    familyRatingContainer: {
      backgroundColor: t.cardBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: t.border,
    },
    familyRatingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    familyMemberName: { flex: 1, fontSize: 13, fontWeight: '600', color: t.textMain, marginRight: 8 },
    starButtonGroup: { flexDirection: 'row', gap: 4 },
    starButton: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 6, backgroundColor: t.chipBg },
    starButtonActive: {
      backgroundColor: t.isDark ? '#332712' : '#FEF9E7',
      borderWidth: 1,
      borderColor: '#E67E22',
    },
    starButtonText: { fontSize: 11, color: t.textMuted, fontWeight: '500' },
    starButtonTextActive: { color: '#E67E22', fontWeight: 'bold' },

    noteInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: t.primaryBorder,
      minHeight: 60,
      fontSize: 14,
      color: t.textMain,
      textAlignVertical: 'top',
    },
    recipeTextInput: {
      backgroundColor: t.inputBg,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: t.borderInput,
      minHeight: 110,
      fontSize: 14,
      color: t.textMain,
      lineHeight: 20,
      textAlignVertical: 'top',
    },

    loadingBox: { alignItems: 'center', paddingVertical: 50 },
    loadingText: { marginTop: 12, color: t.textSub, fontSize: 14, fontWeight: '500' },

    settingToggleRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
    settingOptionBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: 'center',
    },
    settingOptionBtnActive: { backgroundColor: t.primary, borderColor: t.primary },
    settingOptionText: { fontSize: 13, fontWeight: '600', color: t.textSub },
    settingOptionTextActive: { color: '#FFF' },

    memberHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
    memberCountBadge: { fontSize: 11, fontWeight: 'bold', color: t.primary, backgroundColor: t.primaryLight, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 10 },
    memberEditRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 8 },
    memberIndexLabel: { fontSize: 12, fontWeight: 'bold', color: t.textMuted, width: 22 },
    memberNameInput: { flex: 1, backgroundColor: t.inputBg, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, fontSize: 13, color: t.textMain, borderWidth: 1, borderColor: t.borderInput },
    memberDeleteBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#FDE8E8', justifyContent: 'center', alignItems: 'center' },
    memberDeleteBtnText: { color: '#DC3545', fontSize: 13, fontWeight: 'bold' },
    addMemberBtn: { marginTop: 10, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: t.primary, borderStyle: 'dashed', alignItems: 'center' },
    addMemberBtnText: { color: t.primary, fontSize: 12, fontWeight: 'bold' },

    deleteFormBtn: { marginTop: 10, marginBottom: 20, paddingVertical: 12, borderRadius: 10, backgroundColor: t.isDark ? '#3A1E1E' : '#FDE8E8', borderWidth: 1, borderColor: '#F8B4B4', alignItems: 'center' },
    deleteFormBtnText: { color: '#DC3545', fontSize: 14, fontWeight: 'bold' },
    resetDefaultBtn: { marginTop: 10, marginBottom: 20, paddingVertical: 12, borderRadius: 10, backgroundColor: t.isDark ? '#2A2035' : '#F4ECF7', borderWidth: 1, borderColor: '#D2B4DE', alignItems: 'center' },
    resetDefaultBtnText: { color: '#8E44AD', fontSize: 14, fontWeight: 'bold' },

    // 詳細画面
    detailImage: { width: '100%', height: 200, borderRadius: 12, marginBottom: 12 },
    detailTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
    detailTitle: { flex: 1, fontSize: 20, fontWeight: 'bold', color: t.textMain, marginRight: 8 },
    detailCategoryBadge: { backgroundColor: t.primaryLight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 1, borderColor: t.primaryBorder },
    detailCategoryBadgeText: { fontSize: 12, fontWeight: '700', color: t.primary },
    detailUncookedBox: { backgroundColor: '#E8F8F5', paddingVertical: 7, paddingHorizontal: 10, borderRadius: 8, marginVertical: 4, borderWidth: 1, borderColor: '#A3E4D7' },
    detailUncookedText: { fontSize: 12, color: '#27AE60', fontWeight: 'bold' },
    detailFamilyRatingContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginVertical: 6 },
    detailFamilyRatingChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: t.isDark ? '#332712' : '#FEF9E7', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 1, borderColor: '#F9E79F' },
    detailFamilyMemberLabel: { fontSize: 11, fontWeight: '600', color: t.isDark ? '#FAD7A0' : '#7D6608', marginRight: 4 },
    detailFamilyMemberStars: { fontSize: 12, fontWeight: 'bold', color: '#E67E22' },

    // アクションバー
    smartActionBar: { flexDirection: 'row', gap: 6, marginVertical: 8 },
    smartActionBtn: { flex: 1, backgroundColor: t.cardBg, paddingVertical: 9, borderRadius: 8, borderWidth: 1, borderColor: t.border, alignItems: 'center', justifyContent: 'center' },
    smartActionBtnActiveCooking: { backgroundColor: '#DC3545', borderColor: '#DC3545' },
    smartActionBtnActiveRequest: { backgroundColor: '#E67E22', borderColor: '#E67E22' },
    smartActionBtnText: { fontSize: 11, fontWeight: '700', color: t.textMain },
    smartActionBtnTextActive: { color: '#FFF' },

// ★ 「今日作った！」ボタンを上品なカフェトーンに統一
    todayCookedBtn: {
      backgroundColor: t.primaryLight,
      borderWidth: 1,
      borderColor: t.primaryBorder,
      paddingVertical: 11,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    todayCookedBtnText: {
      color: t.primary,
      fontSize: 14,
      fontWeight: 'bold',
    },

    cookingActiveBanner: { backgroundColor: t.isDark ? '#332712' : '#FEF9E7', paddingVertical: 7, paddingHorizontal: 10, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#F9E79F', alignItems: 'center' },
    cookingActiveBannerText: { fontSize: 11, color: '#D35400', fontWeight: 'bold' },
    webLinkButton: { backgroundColor: t.isDark ? '#1A2A3A' : '#EBF5FB', paddingVertical: 9, paddingHorizontal: 12, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: t.isDark ? '#2E4A62' : '#D4E6F1', alignItems: 'center' },
    webLinkButtonText: { color: '#2980B9', fontSize: 13, fontWeight: '600' },
// ★ 味メモの枠を水色から「温かみのあるクリームベージュ」に統一
    noteSection: {
      backgroundColor: '#FFF8F0', // 優しいミルクティー色
      padding: 14,
      borderRadius: 10,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
      borderWidth: 1,
      borderColor: '#F5E7D3',
    },
    noteSectionHeader: {
      fontSize: 13,
      fontWeight: 'bold',
      color: t.primary,
      marginBottom: 4,
    },
    noteText: {
      fontSize: 14,
      color: t.textMain,
      lineHeight: 20,
    },
    noteSectionEmpty: { backgroundColor: t.chipBg, paddingVertical: 9, paddingHorizontal: 12, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: t.border, borderStyle: 'dashed' },
    noteTextEmpty: { fontSize: 12, color: t.textMuted, fontWeight: '500' },

    detailSection: { backgroundColor: t.cardBg, padding: 14, borderRadius: 10, borderWidth: 1, borderColor: t.border, marginBottom: 30 },
    sectionHeader: { fontSize: 15, fontWeight: 'bold', color: t.primary, marginBottom: 8 },
    recipeLineRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: t.border },
    recipeLineRowChecked: { backgroundColor: t.bg, borderRadius: 6 },
    checkIcon: { fontSize: 15, marginRight: 6, marginTop: 2 },
    detailText: { fontSize: 14, color: t.textMain, lineHeight: 22 },
    cookingLineText: { flex: 1, fontSize: 17, color: t.textMain, lineHeight: 26, fontWeight: '500' },
    checkedLineText: { textDecorationLine: 'line-through', color: t.textMuted },
  });