/* eslint-disable react-native/no-unused-styles */
import { StyleSheet, Platform, StatusBar } from 'react-native';

export const getStyles = (t) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: t.bg,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    header: {
      height: 72,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      backgroundColor: t.headerBg,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    headerSideArea: { width: 90, justifyContent: 'center' },
    headerDateText: { fontSize: 13.5, fontWeight: '700', color: t.textMuted, letterSpacing: 0.3 },
    headerTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700', color: t.textMain, letterSpacing: 0.5 },
    headerLogo: { width: 175, height: 54, alignSelf: 'center' },
    headerQuickAddBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      backgroundColor: t.cardBg,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    headerButton: { fontSize: 15, color: t.primary, fontWeight: '600' },
    headerCancelButton: { fontSize: 15, color: t.textMuted, fontWeight: '500' },
    headerSaveButton: { fontSize: 16, fontWeight: '700', color: t.primary },
    editButtonText: { fontSize: 15, color: t.primary, fontWeight: '600' },
    clearBoughtText: { fontSize: 12.5, color: t.primary, fontWeight: '600' },
    clearAllText: { fontSize: 12.5, color: t.accentBordeaux, fontWeight: '600' },

    // ★ 下部ボトムナビゲーションバー（ふんわり丸みと極薄ボーダー）
    bottomNavBar: {
      flexDirection: 'row',
      height: Platform.OS === 'ios' ? 86 : 88,
      paddingBottom: Platform.OS === 'ios' ? 24 : 30,
      backgroundColor: t.navBg,
      borderTopWidth: 1,
      borderTopColor: t.border,
      alignItems: 'center',
      justifyContent: 'space-around',
    },
    navTabItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6,
      borderRadius: 18,
    },
    navTabLabel: {
      fontSize: 10.5,
      fontWeight: '600',
      color: t.textMuted,
      marginTop: 3,
    },
    navTabLabelActive: {
      color: t.primary,
      fontWeight: '700',
    },
    navBadge: {
      position: 'absolute',
      right: -8,
      top: -3,
      backgroundColor: t.primary,
      borderRadius: 999,
      paddingHorizontal: 5,
      paddingVertical: 1,
      minWidth: 16,
      alignItems: 'center',
    },
    navBadgeText: { color: '#FFF', fontSize: 9, fontWeight: 'bold' },

    // ★ ホーム画面（ゆとりのある余白）
    homeScrollView: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 110 },
    headlineBarHome: {
      backgroundColor: t.isDark ? '#261F1A' : '#FFFDF9',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 18,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 2,
    },
    headlineTextHome: { fontSize: 13, fontWeight: '600', color: t.primary, lineHeight: 20 },

    homeSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 14,
      marginBottom: 10,
    },
    homeSectionTitle: { fontSize: 16, fontWeight: '700', color: t.textMain, letterSpacing: 0.3 },

    // ★ 空気のようなシャドウを持つ空白時カード
    homeEmptyCard: {
      backgroundColor: t.cardBg,
      borderRadius: 20,
      padding: 18,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: t.border,
      borderStyle: 'dashed',
    },
    homeEmptyCardTitle: { fontSize: 13.5, fontWeight: '700', color: t.textSub, marginBottom: 5 },
    homeEmptyCardSub: { fontSize: 12, color: t.textMuted, lineHeight: 18 },

    // ★ 今日のオススメ（ごぶさたスタメン）：面で魅せるラグジュアリーカード
    homeRecommendCard: {
      backgroundColor: t.cardBg,
      borderRadius: 24,
      padding: 20,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: t.primaryBorder,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.06,
      shadowRadius: 18,
      elevation: 3,
    },
    homeRecommendLeft: { flex: 1, marginRight: 12 },
    homeRecommendTag: { fontSize: 11.5, fontWeight: '700', color: t.primary, marginBottom: 5, letterSpacing: 0.5 },
    homeRecommendTitle: { fontSize: 17, fontWeight: '700', color: t.textMain, marginBottom: 5 },
    homeRecommendSub: { fontSize: 12, color: t.textMuted },
    homeRecommendBtn: {
      backgroundColor: t.primary,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 999, // カプセルボタン
      shadowColor: t.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 2,
    },
    homeRecommendBtnText: { color: '#FFF', fontSize: 12.5, fontWeight: '700' },

    // 直近の献立
    recentMealCard: {
      backgroundColor: t.cardBg,
      borderRadius: 20,
      padding: 14,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 2,
    },
    recentMealRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 6,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    recentMealDate: { fontSize: 12.5, fontWeight: '700', color: t.primary, width: 55 },
    recentMealTitle: { flex: 1, fontSize: 14, color: t.textMain, fontWeight: '600' },

    // 横スクロールカルーセル（丸みのある幅広カード）
    horizontalCard: {
      width: 170,
      backgroundColor: t.cardBg,
      borderRadius: 20,
      marginRight: 12,
      borderWidth: 1,
      borderColor: t.border,
      overflow: 'hidden',
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.04,
      shadowRadius: 14,
      elevation: 2,
    },
    horizontalThumb: { width: '100%', height: 105, backgroundColor: t.chipBg },
    horizontalThumbPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    horizontalCardBody: { padding: 10 },
    horizontalCardTitle: { fontSize: 13.5, fontWeight: '700', color: t.textMain, marginBottom: 5 },
    horizontalCardMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },

    // レシピ帳画面
    searchBarContainer: {
      backgroundColor: t.headerBg,
      paddingHorizontal: 18,
      paddingTop: 8,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    searchInput: {
      backgroundColor: t.cardBg,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 14.5,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.03,
      shadowRadius: 6,
      elevation: 1,
    },
    filterTabsScroll: { flexDirection: 'row', marginTop: 10 },
    filterTab: {
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: 999, // カプセル形状
      backgroundColor: t.cardBg,
      marginRight: 8,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.02,
      shadowRadius: 4,
      elevation: 1,
    },
    filterTabActive: { backgroundColor: t.primary, borderColor: t.primary },
    filterTabActiveUserOnly: { backgroundColor: t.primary, borderColor: t.primary },
    filterTabActiveRequested: { backgroundColor: '#D97724', borderColor: '#D97724' },
    filterTabActiveWant: { backgroundColor: t.accentSage, borderColor: t.accentSage },
    filterTabActiveBento: { backgroundColor: '#D97724', borderColor: '#D97724' },
    filterTabActiveMealPrep: { backgroundColor: '#3A7CA5', borderColor: '#3A7CA5' },
    filterTabActivePreset: { backgroundColor: '#7D5A8E', borderColor: '#7D5A8E' },
    filterTabText: { fontSize: 12, fontWeight: '600', color: t.textSub },
    filterTabTextActive: { color: '#FFF' },

    listContent: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 120 },
    // ★ レシピ帳カード：ぷっくり角丸 ＆ やわらかシャドウ
    card: {
      flexDirection: 'row',
      backgroundColor: t.cardBg,
      borderRadius: 22,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.05,
      shadowRadius: 14,
      elevation: 2,
    },
    cardRequestedHighlight: {
      borderColor: '#E8A86B',
      backgroundColor: t.isDark ? '#261F1A' : '#FFFDF9',
    },
    thumbnail: { width: 85, height: 85, borderRadius: 16, backgroundColor: t.chipBg },
    thumbnailPlaceholder: { alignItems: 'center', justifyContent: 'center' },
    cardBody: { flex: 1, marginLeft: 14, justifyContent: 'space-between' },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { flex: 1, fontSize: 15.5, fontWeight: '700', color: t.textMain, marginRight: 6 },
    cardBadgesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginVertical: 4 },
    cardBadgeItem: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 999, // カプセル
      backgroundColor: t.chipBg,
    },
    cardBadgeItemText: { fontSize: 10.5, fontWeight: '600', color: t.textSub },
    cardNotes: { fontSize: 12, color: t.primary, lineHeight: 18 },
    cardNotesEmpty: { fontSize: 11.5, color: t.textMuted },
    cardMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
    cardDate: { fontSize: 10.5, color: t.textMuted },

    fab: {
      position: 'absolute',
      right: 20,
      bottom: 35,
      backgroundColor: t.primary,
      paddingVertical: 14,
      paddingHorizontal: 22,
      borderRadius: 999, // 完全なピル形状
      elevation: 6,
      shadowColor: t.primary,
      shadowOpacity: 0.35,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      zIndex: 10,
    },
    fabText: { color: '#FFF', fontSize: 15, fontWeight: '700', letterSpacing: 0.5 },

    // 詳細画面
    detailImage: { width: '100%', height: 220, borderRadius: 22, marginBottom: 14 },
    detailTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    detailTitle: { flex: 1, fontSize: 21, fontWeight: '700', color: t.textMain, letterSpacing: 0.3 },
    detailTagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
    detailTag: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: t.primaryLight,
      borderWidth: 1,
      borderColor: t.primaryBorder,
    },
    detailTagText: { fontSize: 12, fontWeight: '700', color: t.primary },

    bigCookStartBtn: {
      backgroundColor: t.primary,
      paddingVertical: 14,
      borderRadius: 18,
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: t.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    bigCookStartBtnText: { color: '#FFF', fontSize: 15.5, fontWeight: '700', letterSpacing: 0.5 },
    bigCookStartBtnActive: { backgroundColor: t.accentBordeaux, shadowColor: t.accentBordeaux },

    smartActionBar: { flexDirection: 'row', gap: 10, marginBottom: 16 },
    smartActionBtn: {
      flex: 1,
      backgroundColor: t.cardBg,
      paddingVertical: 11,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.03,
      shadowRadius: 6,
      elevation: 1,
    },
    smartActionBtnActiveRequest: { backgroundColor: '#D97724', borderColor: '#D97724' },
    smartActionBtnText: { fontSize: 12.5, fontWeight: '700', color: t.textMain },
    smartActionBtnTextActive: { color: '#FFF' },

    noteSection: {
      backgroundColor: '#FFFDF9',
      padding: 16,
      borderRadius: 20,
      marginBottom: 16,
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.03,
      shadowRadius: 8,
      elevation: 1,
    },
    noteSectionHeader: { fontSize: 13.5, fontWeight: '700', color: t.primary, marginBottom: 5 },
    noteText: { fontSize: 13.5, color: t.textMain, lineHeight: 22 },
    noteSectionEmpty: {
      backgroundColor: t.chipBg,
      paddingVertical: 11,
      paddingHorizontal: 16,
      borderRadius: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: t.border,
      borderStyle: 'dashed',
    },
    noteTextEmpty: { fontSize: 12.5, color: t.textMuted, fontWeight: '500' },

    servingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: t.cardBg,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 16,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: t.border,
    },
    servingLabel: { fontSize: 12.5, fontWeight: '700', color: t.textSub },
    servingChips: { flexDirection: 'row', gap: 6 },
    servingChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: t.chipBg,
    },
    servingChipActive: { backgroundColor: t.primary },
    servingChipText: { fontSize: 11.5, fontWeight: '600', color: t.textSub },
    servingChipTextActive: { color: '#FFF', fontWeight: '700' },

    detailSection: {
      backgroundColor: t.cardBg,
      padding: 20,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: t.border,
      marginBottom: 40,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.04,
      shadowRadius: 14,
      elevation: 2,
    },
    sectionHeader: { fontSize: 16, fontWeight: '700', color: t.primary, marginBottom: 12 },
    recipeLineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    recipeLineRowChecked: { backgroundColor: t.chipBg, borderRadius: 10 },
    checkIcon: { fontSize: 16, marginRight: 8, marginTop: 2 },
    detailText: { fontSize: 14.5, color: t.textMain, lineHeight: 25 },
    cookingLineText: { flex: 1, fontSize: 17, color: t.textMain, lineHeight: 28, fontWeight: '600' },
    checkedLineText: { textDecorationLine: 'line-through', color: t.textMuted },

    // 買い物リスト
    addShoppingBar: {
      flexDirection: 'row',
      backgroundColor: t.headerBg,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
      gap: 10,
    },
    addShoppingInput: {
      flex: 1,
      backgroundColor: t.cardBg,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 9,
      fontSize: 14.5,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.border,
    },
    addShoppingBtn: {
      backgroundColor: t.primary,
      paddingHorizontal: 16,
      justifyContent: 'center',
      borderRadius: 16,
    },
    addShoppingBtnText: { color: '#FFF', fontSize: 13.5, fontWeight: '700' },
    shoppingItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    shoppingItemRowChecked: { opacity: 0.45 },
    shoppingItemCheckArea: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    shoppingCheckIcon: { fontSize: 19, marginRight: 12 },
    shoppingItemText: { fontSize: 15.5, color: t.textMain, fontWeight: '500' },
    shoppingItemTextChecked: { textDecorationLine: 'line-through', color: t.textMuted },
    shoppingItemDeleteBtn: { padding: 8 },
    shoppingItemDeleteText: { fontSize: 14, color: t.accentBordeaux, fontWeight: '700' },

    // 編集画面・設定画面共通
    content: { padding: 18 },
    editScrollContent: { paddingBottom: 120 },
    formCard: {
      backgroundColor: t.cardBg,
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: t.border,
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.04,
      shadowRadius: 14,
      elevation: 2,
    },
    formCardHighlight: {
      backgroundColor: t.isDark ? '#1F1B18' : '#FFFDF9',
      borderLeftWidth: 4,
      borderLeftColor: t.primary,
    },
    formCardHeader: {
      fontSize: 15.5,
      fontWeight: '700',
      color: t.textMain,
      marginBottom: 14,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    formCardHeaderNoBorder: { fontSize: 15.5, fontWeight: '700', color: t.textMain },
    fieldLabel: { fontSize: 13, fontWeight: '700', color: t.textSub, marginBottom: 6 },
    requiredMark: { color: t.accentBordeaux },
    subLabelHelp: { fontSize: 11.5, color: t.textMuted, marginBottom: 10, lineHeight: 17 },

    inputTitle: {
      backgroundColor: t.inputBg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 11,
      fontSize: 15.5,
      fontWeight: '600',
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 14,
    },
    inputRegular: {
      backgroundColor: t.inputBg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 9,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 8,
    },
    categorySelectorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
    categoryChip: {
      backgroundColor: t.chipBg,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 999, // ピル
    },
    categoryChipSelected: { backgroundColor: t.primary },
    categoryChipText: { fontSize: 12.5, fontWeight: '600', color: t.textSub },
    categoryChipTextSelected: { color: '#FFF' },

    tagToggleRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
    tagToggleBtn: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
    },
    tagToggleBtnActive: { backgroundColor: t.primaryLight, borderColor: t.primary },
    tagToggleBtnText: { fontSize: 12.5, color: t.textSub, fontWeight: '600' },
    tagToggleBtnTextActive: { color: t.primary, fontWeight: '700' },

    familyRatingContainer: {
      backgroundColor: t.cardBg,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: t.border,
    },
    familyRatingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 9,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    familyMemberName: { flex: 1, fontSize: 13.5, fontWeight: '600', color: t.textMain, marginRight: 8 },
    starButtonGroup: { flexDirection: 'row', gap: 4 },
    starButton: { paddingVertical: 5, paddingHorizontal: 9, borderRadius: 999, backgroundColor: t.chipBg },
    starButtonActive: { backgroundColor: '#FDF2E4' },
    starButtonText: { fontSize: 11, color: t.textMuted, fontWeight: '500' },
    starButtonTextActive: { color: '#C85A17', fontWeight: '700' },

    noteInput: {
      backgroundColor: t.inputBg,
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: t.borderInput,
      minHeight: 65,
      fontSize: 14,
      color: t.textMain,
      textAlignVertical: 'top',
    },
    recipeTextInput: {
      backgroundColor: t.inputBg,
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: t.borderInput,
      minHeight: 120,
      fontSize: 14,
      color: t.textMain,
      lineHeight: 22,
      textAlignVertical: 'top',
    },

    deleteFormBtn: { marginTop: 12, marginBottom: 20, paddingVertical: 14, borderRadius: 18, backgroundColor: '#FDF2F2', alignItems: 'center' },
    deleteFormBtnText: { color: t.accentBordeaux, fontSize: 14, fontWeight: '700' },
    resetDefaultBtn: { marginTop: 12, marginBottom: 20, paddingVertical: 14, borderRadius: 18, backgroundColor: '#F9F5FB', alignItems: 'center' },
    resetDefaultBtnText: { color: '#7D5A8E', fontSize: 14, fontWeight: '700' },

    settingToggleRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
    settingOptionBtn: {
      flex: 1,
      paddingVertical: 11,
      borderRadius: 14,
      backgroundColor: t.chipBg,
      alignItems: 'center',
    },
    settingOptionBtnActive: { backgroundColor: t.primary },
    settingOptionText: { fontSize: 13, fontWeight: '600', color: t.textSub },
    settingOptionTextActive: { color: '#FFF' },

    familyIdDisplayBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: t.inputBg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: t.borderInput,
      marginBottom: 6,
    },
    familyIdText: { fontSize: 16.5, fontWeight: '700', color: t.primary, letterSpacing: 1.5 },
    familyIdInfoBtn: { backgroundColor: t.primaryLight, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
    familyIdInfoBtnText: { fontSize: 11, fontWeight: '700', color: t.primary },
    regenerateIdBtn: { paddingVertical: 6, alignItems: 'center', marginBottom: 12 },
    regenerateIdBtnText: { fontSize: 12.5, fontWeight: '600', color: t.primary },
    joinFamilyRow: { flexDirection: 'row', gap: 10 },
    joinFamilyInput: {
      flex: 1,
      backgroundColor: t.inputBg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 9,
      fontSize: 14,
      color: t.textMain,
      borderWidth: 1,
      borderColor: t.borderInput,
    },
    joinFamilyBtn: { backgroundColor: t.primary, paddingHorizontal: 18, justifyContent: 'center', borderRadius: 14 },
    joinFamilyBtnText: { color: '#FFF', fontSize: 13.5, fontWeight: '700' },

    memberHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
    memberCountBadge: { fontSize: 11, fontWeight: '700', color: t.primary, backgroundColor: t.primaryLight, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999 },
    memberEditRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 8 },
    memberIndexLabel: { fontSize: 12.5, fontWeight: '700', color: t.textMuted, width: 22 },
    memberNameInput: { flex: 1, backgroundColor: t.inputBg, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 7, fontSize: 13.5, color: t.textMain, borderWidth: 1, borderColor: t.borderInput },
    memberDeleteBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#FDF2F2', justifyContent: 'center', alignItems: 'center' },
    memberDeleteBtnText: { color: t.accentBordeaux, fontSize: 13, fontWeight: '700' },
    addMemberBtn: { marginTop: 12, paddingVertical: 10, borderRadius: 14, borderWidth: 1.5, borderColor: t.primary, borderStyle: 'dashed', alignItems: 'center' },
    addMemberBtnText: { color: t.primary, fontSize: 12.5, fontWeight: '700' },
  });
